[package]
name = "fsm"
version = "0.1.0"
edition = "2021"

[dependencies]
derive_more = "0.99.17"
enum_dispatch = "0.3.8"
heapless = "0.7.16"
paste = "1.0.11"
static_assertions = "1.1.0"
strum = "0.24.1"
strum_macros = "0.24.3"
